<a href="https://colab.research.google.com/github/Waflon/DL_Python/blob/main/Python_Tutorial_For_DL_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Numpy
---



Una de las librerías más usadas para DL (y para casi cualquier proyecto en python) es la de numpy.

In [ ]:
import numpy as np

In [ ]:
numbers = [1, 2, 3, 4, 5]  #List
sum(numbers)

np.mean(numbers)

3.0

In [ ]:
# Se puede usar una función especifica, aplicandola directamente con:
from numpy import mean  #Acá se llama una función de forma específica
mean(numbers)

3.0

In [ ]:
x = np.linspace(1,7,5)  # Rellena hasta tener 5 valores entre 1 y 7
type(x)

numpy.ndarray

In [ ]:
numbers_np = np.array(numbers)

print(type(numbers))
print(type(numbers_np))  

<class 'list'>
<class 'numpy.ndarray'>


Se pueden utilizar listas o numpy.ndarray como argumentos para métodos de numpy

In [ ]:
np.max( numbers )  # look for the biggest number 

5

In [ ]:
n = [ 4, 3, 5, 2, 6, 1, 7]
print(n)
n.sort()  # El método sort modifica la lista original
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
n = [ 4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
np.sort(nn)  # El método de sort de Numpy no modifica la lista original
print(nn)

[4 3 5 2 6 1 7]
[4 3 5 2 6 1 7]


---
#Pandas
---

In [ ]:
import numpy as np
import pandas as pd

#Create random data
np.random.randn()

-1.7233621168912183

In [ ]:
np.random.randn(5)  # Generar un arreglo de 5 indices

array([-0.30160042, -1.60271558,  0.234791  , -0.64517906, -0.71557167])

In [ ]:
np.random.randn(5, 5)  # Generar una Matriz de 5x5

array([[ 0.6925471 ,  0.77621889,  0.29026328,  0.40034294, -0.13751501],
       [-0.23127453, -1.86127238, -0.40007093,  0.24756431,  1.03707395],
       [-0.476336  ,  0.32041685, -0.69717421,  1.07674052, -1.29294428],
       [ 0.0101023 , -0.78323175,  1.18495293, -0.65504847, -0.43379648],
       [-0.04052006,  0.46790869, -1.46609083, -1.16590016, -0.65513014]])

In [ ]:
# Lista de 100 elementos
var1 = np.random.randn(100)*5 + 20
var1

array([24.06697999, 17.31925899, 15.67533038, 18.62666831, 19.78046408,
       22.12762073, 12.39951484, 16.60225178, 23.11128656, 17.37027262,
       24.92027233, 24.53744362, 21.55658014, 23.40053083, 16.65829494,
       22.00323356, 14.17468253, 22.39043759, 19.91443058, 26.18779449,
       15.54495504, 11.6808014 , 24.17517739, 20.007991  , 12.09181652,
       26.98936558, 18.68390159, 20.60815219, 18.75366048, 19.99081415,
       18.28589694, 19.60716122, 13.01964546, 20.86823301, 23.2871262 ,
       20.75858416, 28.09235454, 21.45001901, 19.87032329, 21.83334447,
       23.77195663, 27.31328468, 21.6602977 , 24.97227597, 21.79114976,
       14.66366648, 20.74402438, 19.4082861 , 23.32665665, 13.64831838,
       19.27851769, 20.38261202, 23.44023006, 22.23635771, 16.51044189,
        7.23706714, 11.10248934, 19.58459656, 18.88437867, 21.05254613,
       20.60411433, 21.31460374, 18.43219316, 22.41012931, 10.23538899,
       21.21763387, 16.77886947, 22.93437828, 22.86404713, 12.95

In [ ]:
# Se pueden llenar con booleanos
var2 = np.random.randn(100)>0  # Evalua si el valor es mayor a 0, si ocurre manda True
var2

array([False,  True, False,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True, False, False, False,  True, False, False,
        True,  True,  True, False, False,  True, False,  True,  True,
        True,  True, False, False,  True,  True, False, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False, False, False,  True,  True,  True, False,  True,
        True, False,  True, False, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False])

In [ ]:
# Variable labels
labels = [ 'Temp (C)','Ice Cream']

# Put them together into a dictionary
d = {labels[0]:var1, labels[1]:var2}

#import the dictionary into a pandas dataframe
df = pd.DataFrame(data=d)
type(df)  # Tipo de dato DataFrame

pandas.core.frame.DataFrame

In [ ]:
df

Temp (C)  Ice Cream
0   12.999129       True
1   23.803444       True
2   12.725540      False
3   30.365150       True
4   21.509612       True
..        ...        ...
95  22.377096       True
96  15.318025      False
97  28.374771      False
98  22.064480       True
99  22.391423       True

[100 rows x 2 columns]

In [ ]:
df.mean()

Temp (C)     20.530055
Ice Cream     0.540000
dtype: float64

In [ ]:
# Excercise
# Create a pandas DataFrame with
# Integers going from 0 to 10, their square, and their log

nums = np.array(range(11)) # Crear rango de 0 a 10

df = pd.DataFrame({'Numbers':nums, 'Square':nums**2, 'log':np.log(nums)})
df # El log(0) está indefinido y arrojará un mensaje de advertencia

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


Numbers  Square       log
0         0       0      -inf
1         1       1  0.000000
2         2       4  0.693147
3         3       9  1.098612
4         4      16  1.386294
5         5      25  1.609438
6         6      36  1.791759
7         7      49  1.945910
8         8      64  2.079442
9         9      81  2.197225
10       10     100  2.302585

---
#Getting Help
---

In [ ]:
#Abre menu de ayuda
sum?

In [ ]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [ ]:
import numpy as np
# Recibe ayuda
np.linspace?

In [ ]:
 # Ve el código de la función
np.linspace??

---
#Functions
---

Para crear una funcion partir con la palabra reservada def (Definir) y luego el nombre de la funcion, seguido de ():

In [ ]:
def prueba(): # Creación de la función
  print('Hola')
  #Fin de la funcion
prueba()

Hola


In [ ]:
def sumarPrueba(input1, input2):
  print(input1+input2)
sumarPrueba(1,2)

3


In [ ]:
def sumarPrueba(input1, input2):
  print(f'la suma es: {input1+input2}')
sumarPrueba(1,2)

la suma es: 3


In [ ]:
def sumarPrueba2(input1, input2):
  return input1+input2

resultado = sumarPrueba2(3,5)
resultado

8

In [ ]:
def operaciones(input1, input2):
  product = input1*input2
  suma    = input1+input2
  return product, suma

output1, output2 = operaciones(5, 100)
print(output1)
print(output2)

500
105


---
##Lambda Functions
---

In [ ]:
operacion = lambda x: x**2 -1        # Es como f(x) = (x^2)-1
operacion(5) # f(5) = (5^2)- 1 = 24

24

In [ ]:
# Factorial
import numpy as np

n = 4 # Factorial a evaluar

np.prod(np.arange(1,n+1))  # Product of a range of numbers


24

In [ ]:
def myFactorial(n):
  return np.prod(np.arange(1,n+1))

In [ ]:
myFactorial(5)

120

---
#Using Math library
---

In [ ]:
import math
math.factorial(5)  # funcion de factorial

120

In [ ]:
number = 10
print(myFactorial(number), math.factorial(number))

3628800 3628800


---
##Scope
---

In [ ]:
# Local Scope
# Global Scope
# Rules:
# 1) Variables created inside a function are local
# (Accessible onlyu inside the function)

# 2) Variables created outside a function are global
# (Accessible onlyu inside the function)

In [ ]:
def funcion():
  x = 7  #Declaración local de una variable
  y = 10
  print(x)

In [ ]:
funcion()

7


In [ ]:
#print(x)  # Esto marca error, ya que el x fue declarado de manera local
x = 3
print(3)
funcion()
print(x)

3
7
3


In [ ]:
def funcion2(): # Funcion que no retorna ni un valor
  print(z)

In [ ]:
z = 14
funcion2()

14


---
##Flip a Coin
---

In [ ]:
#Excercise: Write a function that flips a coin N times, and reports the average
import numpy as np

def flipAcoin(n):
  return np.mean(np.random.randn(n) > 0) # Funcion que retorne numeros random y los compare a 0
  #Rendondea a 2 cifras por 

In [ ]:
n = 4000
print(f'{n} coins flips had {round(flipAcoin(n)*100, 2)}% Heads ')  ## Retorna la media de una cantidad n de datos

4000 coins flips had 49.18% Heads 


---
## Copies and Referents of Values

In [ ]:
a = [4, 3]

b = a  # Alvaro es igual a Waflon, ambos referencian a la misma persona
b[0] = 5  # Si modificamos un valor...

print(a)  # Cambia el valor original de a
print(b)

[5, 3]
[5, 3]


In [ ]:
# Podemos almacenar una copia de la lista
b = a[:]
b[1] = 9

print(a)  # No Cambia el valor original de a
print(b)
print(id(a))  #Muestra el espacio de memoria donde se aloja a y b
print(id(b))

[5, 3]
[5, 9]
140660129827648
140660129452192


---
#Copy Dictionaries
---

In [ ]:
# Si intentamos hacer con el diccionario lo mismo que con las listas tendremos un error
# Ya que los tipos de datos se van complejisando, mejor unsa una librería

In [ ]:
import copy
a = {'q':1, 'w':2}
b = copy.deepcopy(a)

print(id(a))  #Muestra el espacio de memoria donde se aloja a y b
print(id(b))

140660129495072
140660129493792


---
# Object Oriented Programming
---

In [ ]:
# class: blueprint for creating a set of attributes and methods
# instance

In [ ]:
class model(object):
  # Constructor method
  def __init__(self, numlayers, numunits, name):
    self.layers = numlayers
    self.units = numunits
    self.name = name
    self.weights = 0

  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} in the model.')

  def trainTheModel(self, x):
    self.weights += x
    return self.weights

  def __str__(self):  # Permite ser llamada para entregar información relevante.
    return f'This is a {self.name} architecture.'

In [ ]:
m1 = model(2, 5, 'CNN')  # Instancia m1 de modelo
#m1.howManyUnits()

In [ ]:
#m1.trainTheModel(-12.5)  # Cada vez que repitamos este codigo, modificaremos el valor del peso
str(m1)  # Llama a la funcion __str__ para mostrar información

'This is a CNN architecture.'

---
## Excercise
---

In [ ]:
# Create a new class
# 1) weights should be a random number matrix of size lazers x units
# 2) Change training method to multiply input X and add input Y
import numpy as np

class model2(object):
  # Constructor method
  def __init__(self, numlayers, numunits, name):
    self.layers = numlayers
    self.units = numunits
    self.name = name
    self.weights = np.random.randn(numlayers, self.units)  # Creacion de la matriz

  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} in the model.')

  def trainTheModel(self, x, y):
    self.weights = self.weights*x+y

  def __str__(self):  # Permite ser llamada para entregar información relevante.
    return f'This is a {self.name} architecture.'

In [ ]:
m2 = model2(2,3, 'X')
m2.weights

array([[-3.36840619,  0.57856453,  2.15252756],
       [ 0.56658596,  0.62608036,  1.25479761]])

In [ ]:
m2.trainTheModel(2,3)  # Se agrandarán más y más los valores ya que estan siendo multimplicados
m2.weights

array([[-4.47362476, 11.31425813, 17.61011024],
       [11.26634385, 11.50432144, 14.01919042]])

In [ ]:
m2.trainTheModel(.2, 0)  # Acá acercamos los valores a 0
m2.weights

array([[-0.0071578 ,  0.01810281,  0.02817618],
       [ 0.01802615,  0.01840691,  0.0224307 ]])

---
#Flow Control
---

In [ ]:
# If statements
# conditional
if True:
  print("This is True!")
if False: # Si la Condicion es Falsa, lo que evalue no será considerado
  print("This is False!")

This is True!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/Github/


[Errno 2] No such file or directory: '/content/drive/MyDrive/Github/'
/content
